#!/usr/bin/env bash

#
# Copyright (C) 2019 Databricks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
PYTHON_EXECUTABLE="${PYTHON_EXECUTABLE:-python}"

set -o pipefail
set -e

if ! hash pytest 2> /dev/null; then
    echo "The pytest command was not found. Please install 'pytest' Python package."
    exit 1
fi

# The current directory of the script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -n "$SPARK_HOME" ]; then
    source $DIR/env_setup.sh
fi

FWDIR="$( cd "$DIR"/.. && pwd )"
cd "$FWDIR"

if [ -n "$KOALAS_USAGE_LOGGER" ]; then
    logopts=(-o log_cli=true -s)
fi

# Runs both doctests and unit tests by default, otherwise hands arguments over to pytest.
# We're doing pytest with `xvfb-run` for CI since without this some of the tests would fail for GUI library because there is no display server.
# The X virtual framebuffer(Xvfb) display server is used to perform all the graphical operations in memory without showing any screen output.
# If you want to run your test with Xvfb, set the environment variable `PYTHON_EXECUTABLE` to `xvfb-run python`.
if [ "$#" = 0 ]; then
    if [[ "$SPARK_VERSION" == 2.3* ]] || [[ "$SPARK_VERSION" == 2.4.1* ]] || [[ "$SPARK_VERSION" == 2.4.2* ]]; then
        # Delta requires Spark 2.4.2+. We skip the related doctests.
        if [[ "$SPARK_VERSION" == 2.3* ]]; then
            $PYTHON_EXECUTABLE -m pytest --cov=databricks -k " -melt -to_delta -read_delta" --verbose --showlocals --doctest-modules databricks "${logopts[@]}"
        else
            $PYTHON_EXECUTABLE -m pytest --cov=databricks -k "-to_delta -read_delta" --verbose --showlocals --doctest-modules databricks "${logopts[@]}"
        fi
    else
        $PYTHON_EXECUTABLE -m pytest --cov=databricks --verbose --showlocals --doctest-modules databricks "${logopts[@]}"
    fi
else
    $PYTHON_EXECUTABLE -m pytest "$@"
fi
